---
- name: Common
  hosts: all
  roles:
    - 'common'
    - role: td-agent
      when: enable_tdagent is undefined or enable_tdagent == '1'
  vars:
    tdagent_conf_template: templates/cassandra-server/td-agent.conf.j2
  gather_facts: no
  become: yes

- name: Cassandra
  hosts: all
  roles:
    - 'java'
    - 'cassandra'
  gather_facts: yes
  become: yes

- name: Set up multiple authorized keys
  hosts: all
  gather_facts: false
  tasks:
    - name: test if ssh_public folder exist
      local_action: stat path="files/ssh_public"
      register: folder_details

    - name: add key
      authorized_key:
        user: centos
        state: present
        key: "{% for key in lookup('fileglob', 'files/ssh_public/*.pub').split(',') %}{{ lookup('file', key) ~ '\n'}}{% endfor %}"
      when: folder_details.stat.isdir is defined and folder_details.stat.isdir
  tags:
  - ssh
